package cn.encmys.ykdz.forest.hypha.parser.token;

public record Token(Type type, String value, int line, int column) {
    public enum Type {TYPEOF, COLON, LEFT_BRACE, RIGHT_BRACE, COMMA, FUNCTION, PLUS, MINUS, MUL, DIV, MOD, EQUALS, IDENTIFIER, NUMBER, STRING, EOF, LEFT_PAREN, RIGHT_PAREN, DOT, IF, THEN, BANG_EQUAL, EQUAL_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, BANG, LOGIC_AND, LOGIC_OR, BIT_AND, BIT_OR, FINISH, ELSE, ELSE_IF, RETURN, POWER, WHILE, FOR, NULL, BREAK, CONTINUE, BOOLEAN, COLON_EQUALS, PLUS_EQUALS, MINUS_EQUALS, MUL_EQUALS, DIV_EQUALS, DO, LET, LEFT_BRAKETS, RIGHT_BRAKETS, VERTICAL_BAR, CONST, EXPORT, IMPORT, AS, FROM, NEW, CHAR, BACKTICK, MOD_EQUALS}
}
