package cn.encmys.ykdz.forest.hyphascript.lexer.token;

import org.jetbrains.annotations.NotNull;

public record Token(@NotNull Type type, @NotNull String value, int line, int column) {
    public enum Type {
        SHIFT_RIGHT, SHIFT_LEFT, NOT, XOR, SLEEP, TYPEOF, COLON, LEFT_BRACE, RIGHT_BRACE, COMMA, FUNCTION, PLUS, MINUS,
        MUL, DIV, MOD, EQUALS, IDENTIFIER, NUMBER, STRING, EOF, LEFT_PAREN, RIGHT_PAREN, DOT, IF, THEN, BANG_EQUALS,
        EQUAL_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, BANG, LOGIC_AND, LOGIC_OR, BIT_AND, BIT_OR, FINISH, ELSE,
        ELSE_IF, RETURN, POWER, WHILE, FOR, NULL, BREAK, CONTINUE, BOOLEAN, COLON_EQUALS, PLUS_EQUALS, MINUS_EQUALS,
        MUL_EQUALS, DIV_EQUALS, DO, LET, LEFT_BRACKET, RIGHT_BRACKET, VERTICAL_BAR, CONST, EXPORT, IMPORT, AS, FROM,
        NEW, CHAR, BACKTICK, TRY, CATCH, FINALLY, QUESTION, ARROW_FUNCTION, SPREAD, CLASS, EXTENDS, STATIC, ASYNC,
        AWAIT, INSTANCE_OF, POWER_EQUALS, JAVA, MOD_EQUALS, IN, OF
    }
}
